### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#35]
Translate and add to Rules

**Comment by martinchristen** [comment]
All attendees of BaselHack must agree and respect the "BaselHack Community Code of Conduct":

The BaselHack community is made up of members from around the globe with a diverse set of skills, personalities, and experiences. It is through these differences that our community experiences great successes and continued growth. When you're working with members of the community, we encourage you to follow these guidelines which help steer our interactions and strive to keep BaselHack a positive, successful, and growing community. 

A member of the BaselHack community is:

**Open**
Members of the community are open to collaboration. We're receptive to constructive comment and criticism, as the experiences and skill sets of other members contribute to the whole of our efforts. We're accepting of all who wish to take part in our activities, fostering an environment where anyone can participate and everyone can make a difference. 

**Considerate**
Members of the community are considerate of their peers -- other BaselHack attendees. We're thoughtful when addressing the efforts of others, keeping in mind that often times the labor was completed simply for the good of the community. We're attentive in our communications, whether in person or online, and we're tactful when approaching differing views. 

**Respectful**
Members of the community are respectful. We're respectful of others, their positions, their skills, their commitments, and their efforts. We're respectful of the volunteer efforts that permeate the BaselHack community. We're respectful of the processes set forth in the community, and we work within them. When we disagree, we are courteous in raising our issues. 
Overall, we're good to each other. We contribute to this community not because we have to, but because we want to. If we remember that, these guidelines will come naturally.

**Comment by teddybeaker** [comment]
Erstellt unter https://github.com/BaselHack/verein/wiki/Code-of-Conduct-(Verhaltenskodex)

@martinchristen , @mabrimo : könnt ihr euch die deutsche Übersetzung anschauen? Änderungen gern grad direkt vornehmen.

**Comment by martinchristen** [comment]
Aus meiner Sicht ok. Habe Kleinigkeiten editiert.

**Comment by mabrimo** [comment]
Aus meiner Sicht ebenfalls ok, habe Kleinigkeiten direkt vorgenommen. 
Vielleicht sollte man unter "rücksichtsvoll" noch einen zusätzlichen Satz ergänzen - was meint ihr?

D Auch gegenüber der uns zur Verfügung gestellten Infrastruktur und Räumlichkeiten sind wir stets rücksichtsvoll und walten entsprechende Sorgfalt. 

E We are also regardful and show care towards the infrastructure and location we are provided.

**Comment by teddybeaker** [comment]
Finde ich gut so, habe es übernommen. Merci euch beiden.
