### ISSUE TITLE
Use http://gitter.im instead of slack?

### ISSUE THREAD

**Issue by culmat** [BaselHack/Verein#63]
Evaluate gitter as a slack alternative

Pro
- one one account is needed (gittter allows to log in with github)

**Comment by schmidchr** [comment]
Just to make sure, the label '2018' indicates this evaluation should be done for the prospective 2018 edition of BaselHack?

**Comment by schmidchr** [comment]
my summary for an analysis on the usefulness and the usage of Slack:

We set up the BaselHack workspace on Slack with the initial intention to facilitate the communication within the organization committee. For this purpose, the usage was moderate, exchanges took mostly place via e-mail (github issues, mailing lists on hostpoint, direct messages via private and professional accounts).

Immediately prior to the event, we set up an additional channel #coaches within our workspace, to facilitate the matching of requests by participants and a number of specialists volunteering to coach on specific topics. The large majority of our ~70 participants registered via the provided link to Slack and our workspace. The public channels including #coaches were sparsely used, possibly due to the oversee-able size of our location, and the resulting direct availability of most of our coaches.

Yet a number of hacking teams set up their own private channels, and in total slightly over 1300 messages were sent over the workspace.
