### ISSUE TITLE
Organize retro

### ISSUE THREAD

**Issue by teddybeaker** [BaselHack/Verein#66]
invite team for retro

Invite other collaborators to party:
- Nadine Bailleux (Basel Area Swiss)
- Françoise Payot (FHNW)
- Valerie Can

**Comment by teddybeaker** [comment]
Will take place on 14th of November

**Comment by teddybeaker** [comment]
@michelpfirter will moderate retro

**Comment by gbwi** [comment]
Do we have a location already?
I wanted to provide location at Adobe but we will have an internal hackathon :-D
...hence no bigger room available.

**Comment by michelpfirter** [comment]
@gbwi 
- no, not as far as i know ... thus, go ahead
- As for the retro i was asked to moderate, are there enough free walls available to use, as well as a flip chart?

@teddybeaker did we discuss how long the retro should last - i think 1h is minimum

**Comment by gbwi** [comment]
@michelpfirter  
Sorry...might not have been clear enough. 
For November 14th and that whole week the big rooms at our office are blocked for 2 internal hackathons so I will NOT be able to provide a room/apero location.

**Comment by teddybeaker** [comment]
@gbwi , @michelpfirter : as far as I remember, @Brenzikofer offered to host at BaselArea.swiss. I guess he didn't get around sending the invitations because he was still busy with the press release.

@michelpfirter: we didn't discuss the time, but I'd go for 1.5h. We are a group that loves to discuss :smile: 💬  Apart from flipcharts/walls, do we also need green and red cards to write on and cluster?

If we want to look at the participants feedback as well, someone would have to extract that from the form beforehand. See https://github.com/BaselHack/verein/issues/55. I can't, am on vacation and will only return on the 14th in the morning.

**Comment by Brenzikofer** [comment]
Dear all,
Yes BaselArea.swiss can host the apero. But 14th is not a good date for as I have a big conference to moderatie the next day…
So, either we find another date – Thursday of that week. Or you can do it then without me in the rooms of BAS …
Sorry for my late response – very busy times
Cheers Thomas

Von: Stefani Gerber [mailto:notifications@github.com]
Gesendet: Donnerstag, 2. November 2017 07:09
An: BaselHack/verein <verein@noreply.github.com>
Cc: Thomas Brenzikofer <thomas.brenzikofer@baselarea.swiss>; Mention <mention@noreply.github.com>
Betreff: Re: [BaselHack/verein] Organize retro (#66)


@gbwi<https://github.com/gbwi> , @michelpfirter<https://github.com/michelpfirter> : as far as I remember, @Brenzikofer<https://github.com/brenzikofer> offered to host at BaselArea.swiss. I guess he didn't get around sending the invitations because he was still busy with the press release.

@michelpfirter<https://github.com/michelpfirter>: we didn't discuss the time, but I'd go for 1.5h. We are a group that loves to discuss 😄 💬 Apart from flipcharts/walls, do we also need green and red cards to write on and cluster?

If we want to look at the participants feedback as well, someone would have to extract that from the form beforehand. See #55<https://github.com/BaselHack/verein/issues/55>. I can't, am on vacation and will only return on the 14th in the morning.

**Comment by teddybeaker** [comment]
There are only 7 people available on that Thursday (opposed to the 16 for the Tuesday). No other date comes close in numbers of people available to attend so I suggest to keep the 14th. I'll check if we could host.

**Comment by Brenzikofer** [comment]
No worries,
We can  host at baselArea.swiss – we just have to decide on how to close the rooms etc.
What time do we start ?
Cheers Thomas

Von: Stefani Gerber [mailto:notifications@github.com]
Gesendet: Donnerstag, 2. November 2017 17:02
An: BaselHack/verein <verein@noreply.github.com>
Cc: Thomas Brenzikofer <thomas.brenzikofer@baselarea.swiss>; Mention <mention@noreply.github.com>
Betreff: Re: [BaselHack/verein] Organize retro (#66)


There are only 7 people available on that Thursday (opposed to the 16 for the Tuesday). No other date comes close in numbers of people available to attend so I suggest to keep the 14th. I'll check if we could host.

**Comment by teddybeaker** [comment]
after some phone calls: Bluesky will host retro and organize the apero. Invitation will follow tomorrow by @domberg

**Comment by domberg** [comment]
We are happy to organize it :) 
![bottish-basel](https://user-images.githubusercontent.com/32460137/32338794-1c09999c-bff6-11e7-9258-2f3a9aade5d6.jpg)
more infos tomorrow...

**Comment by domberg** [comment]
Invitation sent

**Comment by domberg** [comment]
Hi All,
Sorry for the confusion... 
But the time for the Retro and Celebration Event is 18h - 21:30h, my mistake...
Best regards,
Dom

**Comment by schmidchr** [comment]
Hi all, noticed these exchanges only now ...
@michelpfirter : Any specific reason to completely remove the previous text on<br> https://github.com/BaselHack/BaselHack2017/wiki/RETROSPECTIVE ?<br> I fully agree that the raised points could be better structured into 
- "Was good -> to be repeated?" and 
- "Room for improvement -> specific suggestions"
Or do you have other ideas for this? (Not sure if many of the team have noticed the changed wiki page!?)

**Comment by schmidchr** [comment]
@domberg : updates to calendar entries might not always work as expected, FYI I received yesterday via team@baselhack.ch an update to the invitation:
Aktualisierte Einladung: Retro and Celebration BaselHack - Di 14. Nov. 2017 18:00 - **23:00** 
Location: | bluesky IT-Solutions AG, Aeschenvorstadt 36, 4051 Basel, Sitzungszimmer<br>
-> I hope at least the location and the starting time are unchanged ! :)
